repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
        additional_dependencies: [black]

      - id: isort
        name: isort
        entry: isort
        language: python
        types: [python]
        additional_dependencies: [isort]
